#!/usr/bin/env node
// Generates the per-platform key tables and test vectors from the shared JSON so
// the macOS and Windows clients can never disagree about the contract.
//
//   node shared/gen-keymap.mjs
//
// Outputs (checked in, do not edit by hand):
//   endpoint-mac/Sources/RemoteAccessEndpoint/Generated.swift
//   endpoint-win/src/generated.rs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const { keys } = JSON.parse(readFileSync(join(here, 'keymap.json'), 'utf8'));
const vectors = JSON.parse(readFileSync(join(here, 'test-vectors.json'), 'utf8'));
const header = 'GENERATED by shared/gen-keymap.mjs from shared/keymap.json + shared/test-vectors.json. Do not edit.';
const entries = Object.entries(keys);

// ---- Swift -------------------------------------------------------------------
const swift = `// ${header}
import CoreGraphics

enum Generated {
    /// DOM KeyboardEvent.code -> macOS virtual keycode (kVK_*).
    static let macKeyCodes: [String: CGKeyCode] = [
${entries.filter(([, v]) => v.mac !== null).map(([k, v]) => `        "${k}": ${v.mac},`).join('\n')}
    ]

    struct CoordVector { let x, y: Double; let w, h, px, py: Int }
    static let coordVectors: [CoordVector] = [
${vectors.coords.map((c) => `        .init(x: ${c.x}, y: ${c.y}, w: ${c.w}, h: ${c.h}, px: ${c.px}, py: ${c.py}),`).join('\n')}
    ]

    static let messageVectors: [(raw: String, valid: Bool)] = [
${vectors.messages.map((m) => `        (${JSON.stringify(m.raw)}, ${m.valid}),`).join('\n')}
    ]
}
`;
writeFileSync(join(root, 'endpoint-mac/Sources/RemoteAccessEndpoint/Generated.swift'), swift);

// ---- Rust --------------------------------------------------------------------
const rust = `// ${header}
#![allow(dead_code)]

/// DOM KeyboardEvent.code -> (Windows virtual-key, needs KEYEVENTF_EXTENDEDKEY).
pub fn win_vk(code: &str) -> Option<(u16, bool)> {
    Some(match code {
${entries.filter(([, v]) => v.win !== null).map(([k, v]) => `        ${JSON.stringify(k)} => (${v.win}, ${!!v.ext}),`).join('\n')}
        _ => return None,
    })
}

pub struct CoordVector { pub x: f64, pub y: f64, pub w: i32, pub h: i32, pub px: i32, pub py: i32 }
pub const COORD_VECTORS: &[CoordVector] = &[
${vectors.coords.map((c) => `    CoordVector { x: ${c.x.toFixed(4)}, y: ${c.y.toFixed(4)}, w: ${c.w}, h: ${c.h}, px: ${c.px}, py: ${c.py} },`).join('\n')}
];

pub const MESSAGE_VECTORS: &[(&str, bool)] = &[
${vectors.messages.map((m) => `    (${JSON.stringify(m.raw)}, ${m.valid}),`).join('\n')}
];
`;
writeFileSync(join(root, 'endpoint-win/src/generated.rs'), rust);

console.log(`generated ${entries.length} keys, ${vectors.coords.length} coord + ${vectors.messages.length} message vectors`);
